language: java
script: mvn verify
matrix:
  include:
    - dist: trusty
      jdk: openjdk7
    - dist: trusty
      jdk: openjdk8
    - dist: bionic
      jdk: openjdk11
    - dist: bionic
      jdk: openjdk12
